apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-ci-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-ci-app

  template:
    metadata:
      labels:
        app: sample-ci-app

    spec:
      containers:
        - name: sample-ci-app
          image: anhkv97/sample-ci-app:18
          imagePullPolicy: Always

          ports:
            - containerPort: 3000
